// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: comment/job/v1/comment_job.proto

package v1

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const ()

// CommentJobClient is the client API for CommentJob service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommentJobClient interface {
}

type commentJobClient struct {
	cc grpc.ClientConnInterface
}

func NewCommentJobClient(cc grpc.ClientConnInterface) CommentJobClient {
	return &commentJobClient{cc}
}

// CommentJobServer is the server API for CommentJob service.
// All implementations must embed UnimplementedCommentJobServer
// for forward compatibility
type CommentJobServer interface {
	mustEmbedUnimplementedCommentJobServer()
}

// UnimplementedCommentJobServer must be embedded to have forward compatible implementations.
type UnimplementedCommentJobServer struct {
}

func (UnimplementedCommentJobServer) mustEmbedUnimplementedCommentJobServer() {}

// UnsafeCommentJobServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommentJobServer will
// result in compilation errors.
type UnsafeCommentJobServer interface {
	mustEmbedUnimplementedCommentJobServer()
}

func RegisterCommentJobServer(s grpc.ServiceRegistrar, srv CommentJobServer) {
	s.RegisterService(&CommentJob_ServiceDesc, srv)
}

// CommentJob_ServiceDesc is the grpc.ServiceDesc for CommentJob service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommentJob_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.comment.job.v1.CommentJob",
	HandlerType: (*CommentJobServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "comment/job/v1/comment_job.proto",
}
