// Code generated by entc, DO NOT EDIT.

package commentsubject

import (
	"time"
)

const (
	// Label holds the string label denoting the commentsubject type in the database.
	Label = "comment_subject"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOwnerID holds the string denoting the owner_id field in the database.
	FieldOwnerID = "owner_id"
	// FieldCount holds the string denoting the count field in the database.
	FieldCount = "count"
	// FieldNextFloor holds the string denoting the next_floor field in the database.
	FieldNextFloor = "next_floor"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the commentsubject in the database.
	Table = "comment_subject"
)

// Columns holds all SQL columns for commentsubject fields.
var Columns = []string{
	FieldID,
	FieldOwnerID,
	FieldCount,
	FieldNextFloor,
	FieldState,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCount holds the default value on creation for the "count" field.
	DefaultCount int32
	// DefaultNextFloor holds the default value on creation for the "next_floor" field.
	DefaultNextFloor int32
	// DefaultState holds the default value on creation for the "state" field.
	DefaultState int8
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)
