// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CommentContent is the predicate function for commentcontent builders.
type CommentContent func(*sql.Selector)

// CommentIndex is the predicate function for commentindex builders.
type CommentIndex func(*sql.Selector)

// CommentSubject is the predicate function for commentsubject builders.
type CommentSubject func(*sql.Selector)
