// Code generated by entc, DO NOT EDIT.

package commentcontent

import (
	"time"
)

const (
	// Label holds the string label denoting the commentcontent type in the database.
	Label = "comment_content"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldObjID holds the string denoting the obj_id field in the database.
	FieldObjID = "obj_id"
	// FieldOwnerID holds the string denoting the owner_id field in the database.
	FieldOwnerID = "owner_id"
	// FieldRoot holds the string denoting the root field in the database.
	FieldRoot = "root"
	// FieldFloor holds the string denoting the floor field in the database.
	FieldFloor = "floor"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the commentcontent in the database.
	Table = "comment_content"
)

// Columns holds all SQL columns for commentcontent fields.
var Columns = []string{
	FieldID,
	FieldObjID,
	FieldOwnerID,
	FieldRoot,
	FieldFloor,
	FieldMessage,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultMessage holds the default value on creation for the "message" field.
	DefaultMessage string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)
